# Birds CUB dataset
birds_images_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cvpr2016_cub/images'
birds_embedding_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cub_icml'
birds_text_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cvpr2016_cub/text_c10'
birds_dataset_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/text2image/birds.hdf5'
val_split_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cvpr2016_cub/valclasses.txt'
train_split_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cvpr2016_cub/trainclasses.txt'
test_split_path: '/home/haen1012/workspace/GAN-INT-CLS-master/Data/Birds_dataset/cvpr2016_cub/testclasses.txt'
